### ISSUE TITLE
Controller support failure

### ISSUE THREAD

**Issue by AscendedTarnished** [pcrain/Gunfig#1]
This mod makes my PC or ETG itself fail to recognize the controller plugged in when in-game. So, any mod that depends on this makes controller support fail.

**Comment by pcrain** [comment]
This is an extremely common problem with modded Gungeon in general, and not unique to Gunfig. Can you let me know:

- what OS you're on (Windows, Steam Deck, etc.)?
- what type of controller you're using
- whether your controller works with only MtGAPI and Gunfig installed?
- whether your controller works with only MtGAPI and Alexandria installed?
- whether you have multiple controllers plugged in?
- whether you plugged your controller in before or after starting Gungeon?

This will help me verify the source of the problem. Thanks. :slightly_smiling_face:

**Comment by AscendedTarnished** [comment]
Of course. I'm doing this on windows and the problem only occurs when
Gunfig is installed along with MtGAPI. Alexandria doesn't have any issues.

**Comment by pcrain** [comment]
Ah sorry, I see you responded by email and Github apparently didn't send my updated comment. Can you let me know about the rest of the stuff in the edited first comment? Thanks!

**Comment by AscendedTarnished** [comment]
Makes sense, I'll just respond from Github then. But, as I said, Windows. And I am using a singular Xbox one controller. The problem only seems to be occurring with MtGAPI and Gunfig installed, and I tested both before and after starting Gungeon. Both have the same issue. 
The thing is, most of the time it's just interacting with NPC's that stops working. Everything else works fine.
Sorry for the latency.

**Comment by pcrain** [comment]
Well darn. :confused: I also use a normal XBox controller and haven't had issues, so this might take some digging. I'll see what I can find. Thanks for the report!

**Comment by AscendedTarnished** [comment]
You're welcome. Though, sorry to be a bother. It seems to also be happening with my keyboard. I have no idea what could be causing it in terms of code. I wish you good luck.

**Comment by pcrain** [comment]
Actually, since you mentioned the NPC thing specifically, I am wondering if it's patch code I added for letting the coop partner interact with Breach NPCs that's breaking. Can you manually install version 1.0.3 of Gunfig from Thunderstore ( https://thunderstore.io/c/enter-the-gungeon/p/CaptainPretzel/Gunfig/versions/ ) and see if you have the same issue? If so, I think I know what's wrong, and this should be a relatively easy fix.

**Comment by pcrain** [comment]
Oh, and if that doesn't work, can you also send an output log?

```
How to find LogOutput.log

Automatic (r2modman, Thunderstore Mod Manager):
 1. In your target profile, go to settings.
 2. In settings, press "Browse profile folder"
 3. In the opened folder, go to the folder named "BepInEx"
 4. In there you should find a file named LogOutput.log, that's the file you're looking for.

Manual (no mod manager):
 1. Go to your game's directory.
 2. Go to the folder named BepInEx.
 3. In there you should find a file named LogOutput.log, that's the file you're looking for.
 ```

**Comment by AscendedTarnished** [comment]
The 1.0.3 version seems to be letting me interact with NPC's now.
I can still send the output log if you'd prefer.

**Comment by AscendedTarnished** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16324955/LogOutput.log)

**Comment by pcrain** [comment]
Thanks! So good news is that it's pretty much what I thought and should be a relatively simple fix I can get up by the end of the day. :slightly_smiling_face: However, I'm noticing a very large number of startup errors in your mod that indicate you may be missing a very important file for modded Gungeon that could be breaking a lot of mods. Can you please check and verify that you have the following file:

```
<path to steam>/steamapps/common/Enter the Gungeon/BepInEx/monomod/UnityEngine.CoreModule.MTGAPIPatcher.mm.dll
```

It should be automatically installed if you're using r2modman to install mods from Thunderstore, but if you did any kind of manual install, there's a good chance you don't have it. And if you don't have that file, you'll probably run into weird issues with most mods on Thunderstore. Let me know; thanks!

**Comment by AscendedTarnished** [comment]
Understandable, I did do a manual download and it seems like I am missing that file. Do you know how I can get that and put it where its supposed to be? I am assuming I can just use the zip file from the manual r2modman install.

**Comment by pcrain** [comment]
Ah that explains it. :smile: So the file comes with MtGAPI (https://thunderstore.io/c/enter-the-gungeon/p/MtG_API/Mod_the_Gungeon_API/), you can find it inside the `monomod` folder if you're manually downloading it. Just copy it over to:

```
<path to steam>/steamapps/common/Enter the Gungeon/BepInEx/monomod/UnityEngine.CoreModule.MTGAPIPatcher.mm.dll
```

...then try using the latest version of Gunfig again (1.1.1) and see if it still causes issues.

**Comment by AscendedTarnished** [comment]
It seems to still not be working. I went through and replaced the file in every location of the BepInEx pack mod, because at this point I have no idea where it's actually reading from, and updated Gunfig back to 1.1.1. But it still seems to be malfunctioning with the NPCs.

**Comment by AscendedTarnished** [comment]
[LogOutput.log](https://github.com/user-attachments/files/16325258/LogOutput.log)
 
most recent log

**Comment by pcrain** [comment]
Ooh, excellent, thank you! Now that log is cleaned up of other errors, I can see it's most definitely the error with Gunfig I thought it was. I'll have an updated version on Thunderstore hopefully within a few hours, but definitely by the end of the day. Thanks for helping track it down! :smile:

**Comment by AscendedTarnished** [comment]
Of course, sorry about that. I'm still relatively new to this whole thing. But, I'm glad I could help. Thank you for your patience and time.

**Comment by pcrain** [comment]
@AscendedTarnished Sorry to ping you directly, but are you by any chance running Gungeon from a platform other than Steam? I've looked more closely into the error you're getting, and it's basically saying a method that exists in the latest official version of the game (2.1.9) doesn't exist in your version, which makes me think you have a not-full-up-to-date version of the base game. Can you confirm what version of Gungeon you're running? It should be the first number in the bottom right corner of the title screen when you boot up modded Gungeon. E.g., you should be running 2.1.9:

![ss_2024-07-21_15:26:29:983](https://github.com/user-attachments/assets/f7ec1932-5d57-42df-8b5a-af32708dcd5e)

If you're not running 2.1.9, you'll need to update your version of Gungeon to 2.1.9 on whatever platform you've downloaded it through. All mods are built around 2.1.9, and you'll run into much nastier bugs during runs if you're using a version other than 2.1.9.

If you still need extra support, feel free to join the MtG Discord and ping me (@CaptainPretzel) in the #support channel there: https://discord.gg/uT7AwbcpyC

**Comment by AscendedTarnished** [comment]
Makes sense. I just checked my steam and, like you said, it still had it at a previous version. I updated it and gunfig and it seems to have cleared up my issues. I am terribly sorry for the waste of time.

**Comment by pcrain** [comment]
No worries at all, glad I could help. Have fun! :smile:
