### ISSUE TITLE
sometimes auto-firing not working for blashphemy 

### ISSUE THREAD

**Issue by javers42** [pcrain/Gunfig#2]
sometimes, auto-firing for semi-automatic weapons feature 
not working for blashphemy

**Comment by pcrain** [comment]
@javers42 Can you provide more detail on what you mean exactly? :open_mouth: I just tested it and Blasphemy is in fact firing at its maximum fire rate when holding down fire while "Auto-fire Semi-Automatic Weapons" is active.

https://github.com/user-attachments/assets/f5ccfe7d-bf46-4ce6-862e-2c2bbca76b64

**Comment by pcrain** [comment]
I'm unable to reproduce this without more information, so closing for now. Let me know if you have more information you can provide and I can look into it further. :slightly_smiling_face:
