### ISSUE TITLE
Gunfig options menu fails after certain operations

### ISSUE THREAD

**Issue by kleirof** [pcrain/Gunfig#3]
As long as clicking on any one of the options (GAMEPLAY, CONTROLS, VIDEO, AUDIO), then use the ESC key to exit within a short period of time, usually within one second, and then open Mod Config, it will cause the Mod Config menu to fail. The configs inside are missing and the buttons cannot be used.

**Comment by pcrain** [comment]
Yep, my bad. :sweat_smile: That's a known bug and has been been fixed for the next release, which I was holding off on releasing until trying to track down a couple other bugs. 

In the mean time, the issue fixes itself if you 1) start a new run, or if 2) Mod Config is the very first menu you open on the run.

Anywho I'll close this and ping you when this is fixed. :slightly_smiling_face:

**Comment by pcrain** [comment]
Fixed as of 1.1.4, now live on Thunderstore. Thanks for the report! :slightly_smiling_face:

**Comment by kleirof** [comment]
Got the latest version. Thanks.

**Comment by kleirof** [comment]
Well everything else is good except the arrow scroll box with info. They shrink together and collapse. Ex: get into VIDEO, esc, and enter Mod Config, then the boxes in Qol is glitched.
