### ISSUE TITLE
NPC chat not working

### ISSUE THREAD

**Issue by EliLiu0** [pcrain/Gunfig#4]
Everything works pretty much perfectly but for some reason whenever I try to talk to any NPC it wont let me. I  can still interact with other things but only the NPCs are the ones rejecting me.

**Comment by pcrain** [comment]
Can you verify you're running version 2.1.9 of Enter the Gungeon? This is the final official release of the game and the only version that supports mods (every mod will break on any other version). If you're not using version 2.1.9, you'll need to update your game.

![version](https://github.com/user-attachments/assets/b0064d80-afbe-400e-bae8-b60a92159e25)

**Comment by EliLiu0** [comment]
As it turns out after rechecking everything I had a separate mod that wasn't downloaded properly so it ended up conflicting with y'all's mod. My apologies for any time wasted lol

**Comment by pcrain** [comment]
> As it turns out after rechecking everything I had a separate mod that wasn't downloaded properly so it ended up conflicting with y'all's mod. My apologies for any time wasted lol

All good, no worries. Enjoy modded Gungeon friend. :smile:
